### ISSUE TITLE
Phishtank API URL is failing (HTTP 301 received)

### ISSUE THREAD

**Issue by clmcavaney** [joshp23/YOURLS-Phishtank-2.0#10]
G'day,

I am getting a HTTP 301 when I use this plugin.  I think the issue is that the API URL should be https://

https://github.com/joshp23/YOURLS-Phishtank-2.0/blob/5c884a1cd58560eda5c31065291251bc7ba6b3cb/phishtank-2.0/plugin.php#L228

When I tweaked it on my instance the plugin then worked.

Do you want a pull request, or are you happy to make the change?

Regards,
Christopher

**Comment by joshp23** [comment]
Fixed with https://github.com/joshp23/YOURLS-Phishtank-2.0/commit/245e823e33937c32d6a09c4c9c5d8406186da343
