### ISSUE TITLE
Links without http:// or https://

### ISSUE THREAD

**Issue by jirkapas** [joshp23/YOURLS-Phishtank-2.0#9]
Hi,
When i enter a link without http:// or https:// the plugin always returns This domain is blacklisted.

**Comment by joshp23** [comment]
I wonder what your environment is? I just tested this with latest and cannot reproduce this error.

**Comment by jirkapas** [comment]
Now that i tested it more, it seem that only some domains do this. Now i think its a Phishtank problem because when try to shorten just facebook.com or http://facebook.com it always returns domain is blacklisted, but https://facebook.com is ok. Btw i was testing it with YOURLS 1.7.3 and no other active plugins.

**Comment by joshp23** [comment]
Well done. I was going to refer to https://github.com/joshp23/YOURLS-Phishtank-2.0/blob/b0bbdabd76b5d6aa5be2b311a6cc880ad42c50ba/phishtank-2.0/plugin.php#L119

Which will add `http://` to any url submitted without protocol as part of sanitation. There's a filter in that function in YOURLS core which would allow upgrading to encryption by default if available.

**Comment by joshp23** [comment]
...and I just referred myself to https://github.com/joshp23/YOURLS-Phishtank-2.0/blob/b0bbdabd76b5d6aa5be2b311a6cc880ad42c50ba/phishtank-2.0/plugin.php#L119

Which will add `http://` to any url submitted without protocol as part of sanitation. There's a filter in that function in YOURLS core which would allow upgrading to encryption by default if available.
